from os import getenv


class Settings:
    API_TOKEN = getenv("CUSTOMER_VALIDATION_API_TOKEN", "")
    USER_AGENT = getenv("CUSTOMER_VALIDATION_USER_AGENT", "shipay-challenge/1.0")
    COMPANY_API_BASE_URL = getenv("CUSTOMER_VALIDATION_COMPANY_API_BASE_URL", "https://brasilapi.com.br/api/cnpj/v1")
    COMPANY_API_TIMEOUT_SECONDS = float(getenv("CUSTOMER_VALIDATION_COMPANY_API_TIMEOUT_SECONDS", "2.0"))

    CEP_PRIMARY_BASE_URL = getenv("CUSTOMER_VALIDATION_CEP_PRIMARY_BASE_URL", "https://viacep.com.br/ws")
    CEP_SECONDARY_BASE_URL = getenv("CUSTOMER_VALIDATION_CEP_SECONDARY_BASE_URL", "https://brasilapi.com.br/api/cep/v1")
    CEP_API_TIMEOUT_SECONDS = float(getenv("CUSTOMER_VALIDATION_CEP_API_TIMEOUT_SECONDS", "2.0"))

    RETRY_ATTEMPTS = int(getenv("CUSTOMER_VALIDATION_RETRY_ATTEMPTS", "3"))
    RETRY_BASE_DELAY_SECONDS = float(getenv("CUSTOMER_VALIDATION_RETRY_BASE_DELAY_SECONDS", "0.15"))
